// <auto-generated />
using System;
using InventoryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260525114036_AddSampleProducts")]
    partial class AddSampleProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementSystem.Models.AppNotification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("AppNotifications");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "ห้องนั่งเล่น",
                            Description = "โซฟา โต๊ะกลาง ชั้นวาง",
                            ProductLine = "Furniture"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "ห้องนอน",
                            Description = "เตียง ตู้เสื้อผ้า โต๊ะเครื่องแป้ง",
                            ProductLine = "Furniture"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "ห้องทานอาหาร",
                            Description = "โต๊ะอาหาร เก้าอี้",
                            ProductLine = "Furniture"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "ห้องทำงาน",
                            Description = "โต๊ะทำงาน เก้าอี้สำนักงาน",
                            ProductLine = "Furniture"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "จัดเก็บ",
                            Description = "ชั้นวาง ตู้ลิ้นชัก",
                            ProductLine = "Furniture"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "กลางแจ้ง",
                            Description = "เฟอร์นิเจอร์ลาน",
                            ProductLine = "Furniture"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Warehouse",
                            Description = "Main warehouse operations"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Procurement",
                            Description = "Purchasing and receiving"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Sales",
                            Description = "Outbound and customer orders"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Administration",
                            Description = "Office and HR support"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportsToEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ReportsToEmployeeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.EmployeeCategoryAssignment", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("EmployeeCategoryAssignments");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int");

                    b.Property<decimal?>("DepthCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WidthCm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1087),
                            CurrentStock = 15,
                            Description = "โซฟาหนังสังเคราะห์ 3 ที่นั่ง สีเทาเข้ม",
                            Material = "",
                            Price = 12500m,
                            ProductCode = "LR-001",
                            ProductName = "โซฟา 3 ที่นั่ง สีเทา",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1093),
                            CurrentStock = 8,
                            Description = "โซฟามุมขาอลูมิเนียม สีดำ",
                            Material = "",
                            Price = 18900m,
                            ProductCode = "LR-002",
                            ProductName = "โซฟามุม 2 ส่วน",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1096),
                            CurrentStock = 12,
                            Description = "โต๊ะกลางไม้สักแท้ ขนาด 100x50 ซม.",
                            Material = "",
                            Price = 5500m,
                            ProductCode = "LR-003",
                            ProductName = "โต๊ะกลางไม้สัก",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1099),
                            CurrentStock = 20,
                            Description = "ชั้นวางกำแพง 3 ชั้น สีไวท์โอ๊ค",
                            Material = "",
                            Price = 3200m,
                            ProductCode = "LR-004",
                            ProductName = "ชั้นวางกำแพงไม้",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1102),
                            CurrentStock = 10,
                            Description = "เก้าอี้ยาว 2 ที่นั่ง ลูกฟูก",
                            Material = "",
                            Price = 4800m,
                            ProductCode = "LR-005",
                            ProductName = "เก้าอี้ยาว",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1105),
                            CurrentStock = 6,
                            Description = "ตู้ TV สีบีช ความกว้าง 120 ซม.",
                            Material = "",
                            Price = 8900m,
                            ProductCode = "LR-006",
                            ProductName = "ตู้ TV ไม้อัด",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1108),
                            CurrentStock = 25,
                            Description = "โคมไฟโมเดิร์น โลหะสีดำ",
                            Material = "",
                            Price = 1500m,
                            ProductCode = "LR-007",
                            ProductName = "โคมไฟตั้งพื้น",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1111),
                            CurrentStock = 14,
                            Description = "เก้าอี้นวม หนนุนสั่ง",
                            Material = "",
                            Price = 3500m,
                            ProductCode = "LR-008",
                            ProductName = "เก้าอี้นวม",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1114),
                            CurrentStock = 5,
                            Description = "โต๊ะเกมลาดสีคอนกรีต",
                            Material = "",
                            Price = 6800m,
                            ProductCode = "LR-009",
                            ProductName = "โต๊ะเกม",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1117),
                            CurrentStock = 4,
                            Description = "เตียงนอน ขนาด 150x200 ซม. ไม้สัก",
                            Material = "",
                            Price = 22000m,
                            ProductCode = "BR-001",
                            ProductName = "เตียงนอน ขนาด Queen",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1120),
                            CurrentStock = 7,
                            Description = "เตียงนอน ขนาด 90x200 ซม. ไม้ยาง",
                            Material = "",
                            Price = 9500m,
                            ProductCode = "BR-002",
                            ProductName = "เตียงนอน ขนาด Single",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1123),
                            CurrentStock = 5,
                            Description = "ตู้เสื้อผ้า 2 บาน สีขาว",
                            Material = "",
                            Price = 7800m,
                            ProductCode = "BR-003",
                            ProductName = "ตู้เสื้อผ้า 2 บาน",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1126),
                            CurrentStock = 3,
                            Description = "ตู้เสื้อผ้า 3 บาน กระจก ไม้ลัดดา",
                            Material = "",
                            Price = 12500m,
                            ProductCode = "BR-004",
                            ProductName = "ตู้เสื้อผ้า 3 บาน",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1129),
                            CurrentStock = 8,
                            Description = "โต๊ะเครื่องแป้งพร้อมกระจก สีเคลือบ",
                            Material = "",
                            Price = 5200m,
                            ProductCode = "BR-005",
                            ProductName = "โต๊ะเครื่องแป้ง",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1132),
                            CurrentStock = 18,
                            Description = "ที่นอน ฟอมความหนาแน่นสูง 5 นิ้ว",
                            Material = "",
                            Price = 3500m,
                            ProductCode = "BR-006",
                            ProductName = "ที่นอน ฟอม 5 นิ้ว",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1135),
                            CurrentStock = 50,
                            Description = "หมอนข้าง หมอกฟอมยาง",
                            Material = "",
                            Price = 600m,
                            ProductCode = "BR-007",
                            ProductName = "หมอนข้าง",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1138),
                            CurrentStock = 12,
                            Description = "ผ้าม่านกันแสง สีเบจ",
                            Material = "",
                            Price = 2800m,
                            ProductCode = "BR-008",
                            ProductName = "ผ้าม่านห้องนอน",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 2,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1140),
                            CurrentStock = 6,
                            Description = "ตะแกรงหัวเตียง สีทอง",
                            Material = "",
                            Price = 4500m,
                            ProductCode = "BR-009",
                            ProductName = "ตะแกรงหัวเตียง",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1144),
                            CurrentStock = 3,
                            Description = "โต๊ะอาหาร ไม้สักแท้ 6 ที่นั่ง",
                            Material = "",
                            Price = 16800m,
                            ProductCode = "DR-001",
                            ProductName = "โต๊ะอาหาร ไม้สัก 6 ที่",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1147),
                            CurrentStock = 5,
                            Description = "โต๊ะอาหาร ไม้ยาง 4 ที่นั่ง",
                            Material = "",
                            Price = 8900m,
                            ProductCode = "DR-002",
                            ProductName = "โต๊ะอาหาร 4 ที่",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1150),
                            CurrentStock = 24,
                            Description = "เก้าอี้อาหาร หนังสังเคราะห์ สีดำ",
                            Material = "",
                            Price = 1850m,
                            ProductCode = "DR-003",
                            ProductName = "เก้าอี้อาหาร หนัง",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1152),
                            CurrentStock = 20,
                            Description = "เก้าอี้อาหาร ไม้บีช สีธรรมชาติ",
                            Material = "",
                            Price = 2200m,
                            ProductCode = "DR-004",
                            ProductName = "เก้าอี้อาหาร ไม้",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1155),
                            CurrentStock = 4,
                            Description = "ตู้เก็บจาน 2 บาน กระจก",
                            Material = "",
                            Price = 6500m,
                            ProductCode = "DR-005",
                            ProductName = "ตู้เก็บจาน",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1158),
                            CurrentStock = 8,
                            Description = "โคมไฟแขวนทรงสี่เหลี่ยม",
                            Material = "",
                            Price = 3200m,
                            ProductCode = "DR-006",
                            ProductName = "โคมไฟห้องทานอาหาร",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1161),
                            CurrentStock = 6,
                            Description = "พรมสำหรับห้องทานอาหาร",
                            Material = "",
                            Price = 4500m,
                            ProductCode = "DR-007",
                            ProductName = "พรม 150x200 ซม.",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1164),
                            CurrentStock = 3,
                            Description = "ตู้บาร์ 1 บาน สีวอลนัท",
                            Material = "",
                            Price = 5800m,
                            ProductCode = "DR-008",
                            ProductName = "ตู้บาร์ไม้",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 3,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1167),
                            CurrentStock = 2,
                            Description = "โต๊ะขยายไม้สัก ขนาด 120-160",
                            Material = "",
                            Price = 18500m,
                            ProductCode = "DR-009",
                            ProductName = "โต๊ะขยาย ไม้สัก",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1208),
                            CurrentStock = 10,
                            Description = "โต๊ะทำงาน ไม้อัด 120 ซม.",
                            Material = "",
                            Price = 5200m,
                            ProductCode = "OF-001",
                            ProductName = "โต๊ะทำงาน 120 ซม.",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1211),
                            CurrentStock = 7,
                            Description = "โต๊ะทำงาน ไม้ลัดดา 150 ซม.",
                            Material = "",
                            Price = 6800m,
                            ProductCode = "OF-002",
                            ProductName = "โต๊ะทำงาน 150 ซม.",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1214),
                            CurrentStock = 12,
                            Description = "เก้าอี้สำนักงาน ปรับความสูงได้",
                            Material = "",
                            Price = 4200m,
                            ProductCode = "OF-003",
                            ProductName = "เก้าอี้สำนักงาน ปรับความสูง",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1217),
                            CurrentStock = 5,
                            Description = "เก้าอี้บอส หนัง ห้อแขนปรับได้",
                            Material = "",
                            Price = 6500m,
                            ProductCode = "OF-004",
                            ProductName = "เก้าอี้บอสสีดำ",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1220),
                            CurrentStock = 8,
                            Description = "ชั้นหนังสือ 5 ชั้น ไม้ลัดดา",
                            Material = "",
                            Price = 3800m,
                            ProductCode = "OF-005",
                            ProductName = "ชั้นหนังสือ 5 ชั้น",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1223),
                            CurrentStock = 6,
                            Description = "ตู้ลิ้นชัก ลูกลื่น สีเทา",
                            Material = "",
                            Price = 4500m,
                            ProductCode = "OF-006",
                            ProductName = "ตู้ลิ้นชัก 3 ชั้น",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1226),
                            CurrentStock = 20,
                            Description = "แท่นวางจอคอมพิวเตอร์ ปรับความสูงได้",
                            Material = "",
                            Price = 1200m,
                            ProductCode = "OF-007",
                            ProductName = "แท่นวางจอ",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1229),
                            CurrentStock = 30,
                            Description = "ไฟจอปืนกลาง LED ขาว",
                            Material = "",
                            Price = 800m,
                            ProductCode = "OF-008",
                            ProductName = "ไฟจอปืนกลาง",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 4,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1232),
                            CurrentStock = 9,
                            Description = "โต๊ะแล็ปทอปแบบยางสด",
                            Material = "",
                            Price = 3500m,
                            ProductCode = "OF-009",
                            ProductName = "โต๊ะแล็ป",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1235),
                            CurrentStock = 14,
                            Description = "ชั้นวาง 5 ชั้น เหล็กสีดำ",
                            Material = "",
                            Price = 2500m,
                            ProductCode = "ST-001",
                            ProductName = "ชั้นวาง 5 ชั้น เหล็ก",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1238),
                            CurrentStock = 10,
                            Description = "ชั้นวาง 4 ชั้น ไม้บีช",
                            Material = "",
                            Price = 3500m,
                            ProductCode = "ST-002",
                            ProductName = "ชั้นวาง 4 ชั้น ไม้",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1241),
                            CurrentStock = 5,
                            Description = "ตู้ลิ้นชัก 6 ชั้น ลูกลื่น",
                            Material = "",
                            Price = 5800m,
                            ProductCode = "ST-003",
                            ProductName = "ตู้ลิ้นชัก 6 ชั้น",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1244),
                            CurrentStock = 6,
                            Description = "ตู้เก็บสิ่งของ 2 บาน 3 ชั้น",
                            Material = "",
                            Price = 4200m,
                            ProductCode = "ST-004",
                            ProductName = "ตู้เก็บสิ่งของ",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1247),
                            CurrentStock = 16,
                            Description = "ลังเก็บสิ่งของ ไม้สน",
                            Material = "",
                            Price = 2200m,
                            ProductCode = "ST-005",
                            ProductName = "ลังเก็บสิ่งของ",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1250),
                            CurrentStock = 40,
                            Description = "บล็อกเก็บสิ่งของ ผ้าใบ",
                            Material = "",
                            Price = 800m,
                            ProductCode = "ST-006",
                            ProductName = "บล็อกเก็บสิ่งของ",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1252),
                            CurrentStock = 100,
                            Description = "กล่องเก็บของ PP ขนาดใหญ่",
                            Material = "",
                            Price = 350m,
                            ProductCode = "ST-007",
                            ProductName = "กล่องเก็บของ PP",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1255),
                            CurrentStock = 12,
                            Description = "ชั้นวางกำแพง 3 ชั้น สีขาว",
                            Material = "",
                            Price = 2800m,
                            ProductCode = "ST-008",
                            ProductName = "ชั้นวางกำแพง 3 ชั้น",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 5,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1258),
                            CurrentStock = 20,
                            Description = "ตะกร้าเก็บของ เหล็กสีดำ",
                            Material = "",
                            Price = 1500m,
                            ProductCode = "ST-009",
                            ProductName = "ตะกร้าเก็บของ",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 6,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1261),
                            CurrentStock = 4,
                            Description = "โต๊ะสนามเหล็กเกาะลม",
                            Material = "",
                            Price = 4500m,
                            ProductCode = "OD-001",
                            ProductName = "โต๊ะสนามเหล็ก",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 6,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1264),
                            CurrentStock = 18,
                            Description = "เก้าอี้สนาม พลาสติก สีส้ม",
                            Material = "",
                            Price = 1200m,
                            ProductCode = "OD-002",
                            ProductName = "เก้าอี้สนาม",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 6,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1267),
                            CurrentStock = 5,
                            Description = "ร่มสนาม ขนาด 2.5 ม. สีทอง",
                            Material = "",
                            Price = 3500m,
                            ProductCode = "OD-003",
                            ProductName = "ร่มสนาม",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 6,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1270),
                            CurrentStock = 8,
                            Description = "เก้าอี้พักผ่อนกลางแจ้ง",
                            Material = "",
                            Price = 2800m,
                            ProductCode = "OD-004",
                            ProductName = "เก้าอี้พักผ่อน",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 6,
                            Color = "",
                            CreatedDate = new DateTime(2026, 5, 25, 18, 40, 31, 704, DateTimeKind.Local).AddTicks(1273),
                            CurrentStock = 3,
                            Description = "ชุดโต๊ะเก้าอี้บาร์ 3 ชิ้น",
                            Material = "",
                            Price = 6500m,
                            ProductCode = "OD-005",
                            ProductName = "ชุดโต๊ะเก้าอี้บาร์",
                            Unit = "ชิ้น",
                            WarehouseLocation = ""
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Employee",
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AppNotification", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AuditLog", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InventoryManagementSystem.Models.Employee", "ReportsTo")
                        .WithMany("DirectReports")
                        .HasForeignKey("ReportsToEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InventoryManagementSystem.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("InventoryManagementSystem.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("ReportsTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.EmployeeCategoryAssignment", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.Category", "Category")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.Employee", "Employee")
                        .WithMany("CategoryAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.InventoryTransaction", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.User", "CreatedByUser")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Product", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.User", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Category", b =>
                {
                    b.Navigation("EmployeeAssignments");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("CategoryAssignments");

                    b.Navigation("DirectReports");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Product", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Employee");

                    b.Navigation("InventoryTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
